spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            #连接超时时间
            connectTimeout: 10000
            #读取超时时间
            readTimeout: 10000
  profiles:
    active: dev