server:
  port: 9988

spring:
  cloud:
    openfeign:
      httpclient:
        enabled: true
        hc5:
          enabled: true
      config:
        cloud-payment-service:
          connectTimeout: 5000
          readTimeout: 5000
      compression:
        request:
          enabled: true
          min-request-size: 2048 #最小触发压缩的大小
          mime-types: text/xml,application/xml,application/json #触发压缩数据类型
        response:
          enabled: true
logging:
  level:
    com:
      atguigu:
        cloud:
          apis:
            PayFeignApi: debug
